#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyquery
Version  : 1.2.9
Release  : 18
URL      : https://pypi.python.org/packages/source/p/pyquery/pyquery-1.2.9.zip
Source0  : https://pypi.python.org/packages/source/p/pyquery/pyquery-1.2.9.zip
Summary  : A jquery-like library for python
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pyquery-python
BuildRequires : PasteDeploy
BuildRequires : WSGIProxy2
BuildRequires : WebOb
BuildRequires : WebTest
BuildRequires : beautifulsoup4
BuildRequires : coverage
BuildRequires : cssselect
BuildRequires : lxml
BuildRequires : nose
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pyquery
BuildRequires : python-dev
BuildRequires : python-mock
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six
BuildRequires : waitress

%description
pyquery: a jquery-like library for python
=========================================

%package python
Summary: python components for the pyquery package.
Group: Default

%description python
python components for the pyquery package.


%prep
%setup -q -n pyquery-1.2.9

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=intel.com,localhost
nosetests || :
%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}
python3 setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
